/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AllocationAllocationResponse struct {
	GameServerName string `json:"gameServerName,omitempty"`
	Ports []AllocationResponseGameServerStatusPort `json:"ports,omitempty"`
	Address string `json:"address,omitempty"`
	NodeName string `json:"nodeName,omitempty"`
	Source string `json:"source,omitempty"`
}
