/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AllocationRequestSchedulingStrategy string

// List of AllocationRequestSchedulingStrategy
const (
	PACKED AllocationRequestSchedulingStrategy = "Packed"
	DISTRIBUTED AllocationRequestSchedulingStrategy = "Distributed"
)
