/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// LabelSelector used for finding a GameServer with matching labels.
type AllocationLabelSelector struct {
	// Labels to match.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}
