/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Specifies settings for multi-cluster allocation.
type AllocationMultiClusterSetting struct {
	// If set to true, multi-cluster allocation is enabled.
	Enabled bool `json:"enabled,omitempty"`
	// Selects multi-cluster allocation policies to apply. If not specified, all multi-cluster allocation policies are to be applied.
	PolicySelector *AllocationLabelSelector `json:"policySelector,omitempty"`
}
