/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The gameserver port info that is allocated.
type AllocationResponseGameServerStatusPort struct {
	Name string `json:"name,omitempty"`
	Port int32 `json:"port,omitempty"`
}
