/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// PlayerSelector is filter for player capacity values. minAvailable should always be less or equal to maxAvailable.
type AllocationPlayerSelector struct {
	MinAvailable string `json:"minAvailable,omitempty"`
	MaxAvailable string `json:"maxAvailable,omitempty"`
}
