/*
 * proto/allocation/allocation.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// GameServerSelector used for finding a GameServer with matching filters.
type AllocationGameServerSelector struct {
	// Labels to match.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
	GameServerState *GameServerSelectorGameServerState `json:"gameServerState,omitempty"`
	Players *AllocationPlayerSelector `json:"players,omitempty"`
}
