# Copyright 2023 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v4beta9
kind: Config
manifests:
  rawYaml:
    - open-match.yaml
    - agones-allocator-vs.yaml
  helm:
    releases:
      - name: open-match
        namespace: open-match
        repo: https://open-match.dev/chart/stable
        remoteChart: open-match
        version: 1.8.0
        setValues:
          prometheus.enabled: false
          grafana.enabled: false
          jaeger.enabled: false
          open-match-override.enabled: true
          open-match-customize.enabled: true
          open-match-customize.evaluator.enabled: true
          open-match-core.redis.enabled: false
          # open-match-core.redis.hostname: redis -- set through Cloud Deploy by convention
          # open-match-core.redis.port: 6379 -- set through Cloud Deploy by convention
          open-match-core.redis.pool.maxIdle: 500
          open-match-core.redis.pool.maxActive: 500
          open-match-core.redis.pool.idleTimeout: 0
          open-match-core.redis.pool.healthCheckTimeout: 300ms

deploy:
  kubectl:
    flags:
      apply:
        - --server-side # Avoid the "Too long: must have at most 262144 bytes" problem
        - --force-conflicts
  tolerateFailuresUntilDeadline: true # Fixes startup timeouts
