# Copyright 2023 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

serviceAccount: projects/${PROJECT_ID}/serviceAccounts/cloudbuild-cicd@${PROJECT_ID}.iam.gserviceaccount.com
steps:

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-agones
    dir: agones
    script: |
      gcloud deploy releases create deploy-$(date +'%Y%m%d%H%M%S') \
      --annotations=cloud_build=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID \
      --delivery-pipeline agones-deploy-pipeline \
      --skaffold-file skaffold.yaml \
      --region us-central1
    automapSubstitutions: true

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-open-match
    dir: open-match
    script: |
      gcloud deploy releases create deploy-$(date +'%Y%m%d%H%M%S') \
      --annotations=cloud_build=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID \
      --delivery-pipeline global-game-open-match \
      --skaffold-file skaffold.yaml \
      --region us-central1
    automapSubstitutions: true

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
tags:
  - global-game-demo
  - platform
